export const USER_REQUEST = 'USER_REQUEST';
export const USER_RESULTS = 'USER_RESULTS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';

export const USER_LIST_RESULTS = 'USERS_RESULTS';
export const USER_LIST_LOADING = 'USER_LIST_LOADING';

export const METRICS = 'METRICS';
export const METRICS_LOADING = 'METRICS_LOADING';

export const USER_FEEDBACK = 'USER_FEEDBACK';
export const USER_FEEDBACK_AGGREGATED = 'USER_FEEDBACK_AGGREGATED';

export const QUESTIONS_LIST_REQUEST = 'QUESTIONS_LIST_REQUEST';
export const QUESTIONS_LIST_RESULT = 'QUESTIONS_LIST_RESULT';
export const QUESTION_SELECT_EDIT = 'QUESTION_SELECT_EDIT';





