# Generated by Django 2.2 on 2019-04-29 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('300*250', '300*250'), ('300*600', '300*600')], default='', max_length=150, null=True, verbose_name='size')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.TextField(default='', verbose_name='companyname')),
                ('bannerloads', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='title')),
                ('pagerole', models.TextField(default='', verbose_name='pagerole')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.TextField(default='', verbose_name='companyname')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('totalmoney', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RfCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.TextField(default='', verbose_name='companyname')),
                ('bannerloads', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webaddress', models.TextField(default='', verbose_name='webaddress')),
                ('site_status', models.TextField(choices=[('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='', verbose_name='site_status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='name')),
                ('widgettitle', models.TextField(default='', verbose_name='widgettitle')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('subtype', models.TextField(blank=True, default='', null=True, verbose_name='subtype')),
                ('column', models.TextField(blank=True, default='', null=True, verbose_name='column')),
                ('rows', models.TextField(blank=True, default='', null=True, verbose_name='rows')),
                ('wid', models.TextField(blank=True, default='', null=True, verbose_name='subtype')),
                ('css', models.TextField(blank=True, default='', null=True, verbose_name='css')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Webmoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('currency', models.TextField(default='', verbose_name='currency')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('wmz', models.TextField(default='', verbose_name='wmz')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(default='', verbose_name='subject')),
                ('priority', models.TextField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent'), ('Immediate', 'Immediate')], default='', verbose_name='priority')),
                ('status', models.TextField(choices=[('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='', verbose_name='site_status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('currency', models.TextField(blank=True, default='', null=True, verbose_name='currency')),
                ('country', models.TextField(blank=True, default='', null=True, verbose_name='country')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('payeename', models.TextField(blank=True, default='', null=True, verbose_name='payeename')),
                ('paypalemail', models.TextField(default='', verbose_name='paypalemail')),
                ('payeephone', models.TextField(blank=True, default='', null=True, verbose_name='payeephone')),
                ('payeeaddress', models.TextField(blank=True, default='', null=True, verbose_name='payeeaddress')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payoneer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('payeename', models.TextField(default='', verbose_name='payeename')),
                ('country', models.TextField(default='', verbose_name='country')),
                ('paypalemail', models.TextField(default='', verbose_name='paypalemail')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.TextField(default='', verbose_name='total')),
                ('payment_status', models.TextField(choices=[('Waiting For Payment', 'Waiting For Payment'), ('Paid', 'Paid'), ('Payment Canceled', 'Payment Canceled'), ('In Progress', 'In Progress')], default='', verbose_name='payment_status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='text')),
                ('addedby', models.TextField(choices=[('Admin', 'Admin'), ('User', 'User')], default='', verbose_name='addedby')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.Support')),
            ],
        ),
        migrations.CreateModel(
            name='Epayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('ewallet', models.TextField(default='', verbose_name='ewallet')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnername', models.TextField(blank=True, default='', null=True)),
                ('head', models.TextField(blank=True, default='', null=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('ratio', models.PositiveIntegerField(blank=True, default='', null=True)),
                ('bannersize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BannerSize')),
            ],
        ),
    ]
