# Generated by Django 2.0.6 on 2019-03-10 18:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
