# Generated by Django 2.0.6 on 2019-03-10 20:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190310_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
