# Generated by Django 2.0.6 on 2019-03-11 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190310_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
