# Generated by Django 2.0.6 on 2019-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_questionanswer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='has_contradicting',
            field=models.BooleanField(default=False),
        ),
    ]
