# Generated by Django 2.0.6 on 2019-03-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_has_contradicting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default='')),
                ('uuid', models.TextField(default='')),
                ('value', models.TextField(default='')),
                ('solved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('solved_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaptchaTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default='')),
                ('counter', models.IntegerField(default=0)),
                ('last_trigger_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='captchatrigger',
            index=models.Index(fields=['ip', 'last_trigger_date'], name='survey_capt_ip_6c7a48_idx'),
        ),
    ]
