# Generated by Django 2.0.6 on 2019-03-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190311_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='tag',
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('textarea', 'textarea'), ('radio', 'radio'), ('checkbox', 'checkbox')], default='radio', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=512),
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='tags',
        ),
        migrations.AddField(
            model_name='choice',
            name='tags',
            field=models.ManyToManyField(to='survey.Tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='survey.Tag'),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='tags',
            field=models.ManyToManyField(to='survey.Tag'),
        ),
    ]
