# Generated by Django 2.0.6 on 2019-03-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20190311_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['text']},
        ),
    ]
