# Generated by Django 2.0.6 on 2019-03-11 23:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20190311_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyuser',
            name='tags',
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
