# Generated by Django 2.0.6 on 2019-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20190311_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyuser',
            options={'ordering': ['provider']},
        ),
        migrations.AddIndex(
            model_name='captcha',
            index=models.Index(fields=['ip', 'uuid'], name='survey_capt_ip_c520d1_idx'),
        ),
        migrations.AddIndex(
            model_name='captcha',
            index=models.Index(fields=['uuid'], name='survey_capt_uuid_119a88_idx'),
        ),
        migrations.AddIndex(
            model_name='captchatrigger',
            index=models.Index(fields=['ip'], name='survey_capt_ip_1c3768_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['question', 'survey'], name='survey_ques_questio_077872_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyuser',
            index=models.Index(fields=['provider'], name='survey_surv_provide_e7d2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['text'], name='survey_tag_text_252a19_idx'),
        ),
    ]
