# Generated by Django 2.0.6 on 2019-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20190317_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='provider_user_id',
            field=models.TextField(blank=True, default='', verbose_name='provider_user_id'),
        ),
    ]
