# Generated by Django 2.0.6 on 2019-03-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_price'),
    ]

    operations = [
        migrations.RunSQL(
            '''ALTER TABLE survey_surveyuser ALTER COLUMN provider DROP NOT NULL'''
        ),
        migrations.RunSQL(
            '''UPDATE survey_surveyuser SET provider=null;'''
        ),
        migrations.RemoveIndex(
            model_name='surveyuser',
            name='survey_surv_provide_e7d2ee_idx',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='impression_price',
        ),
        migrations.AddField(
            model_name='provider',
            name='bitcoin_address',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='provider',
            name='payout_method',
            field=models.CharField(choices=[('default', 'Default - manual end of month'), ('user_bitcoin', 'User bitcoin - using faucethub each postback'), ('provider_bitcoin', 'Provider bitcoin - using faucethub, end of day')], default='default', max_length=8),
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='bitcoin_address',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Provider'),
        ),
        migrations.AddIndex(
            model_name='surveyuser',
            index=models.Index(fields=['provider'], name='survey_surv_provide_d506f8_idx'),
        ),
    ]
