# Generated by Django 2.0.6 on 2019-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190328_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='bitcoin_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='provider',
            name='payout_method',
            field=models.CharField(choices=[('default', 'Default - manual end of month'), ('user_bitcoin', 'User bitcoin - using faucethub each postback'), ('provider_bitcoin', 'Provider bitcoin - using faucethub, end of day')], default='default', max_length=32),
        ),
    ]
