# Generated by Django 2.0.6 on 2019-03-31 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20190328_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(default='', max_length=256)),
                ('amount', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Rejected')], default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sent', models.DateTimeField(default=None, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Provider')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(default='', max_length=256)),
                ('amount', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Rejected')], default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sent', models.DateTimeField(default=None, null=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='provider_user_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
