# Generated by Django 2.0.6 on 2019-03-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20190331_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='providertransaction',
            name='payout_currency',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='providertransaction',
            name='payout_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providertransaction',
            name='payout_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providertransaction',
            name='payout_user_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='payout_currency',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='payout_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='payout_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='payout_user_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
