# Generated by Django 2.0.6 on 2019-04-01 04:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20190331_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btcprice',
            options={'ordering': ['-date'], 'verbose_name': 'Price - BTC'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['country'], 'verbose_name': 'Price - USD'},
        ),
        migrations.AlterModelOptions(
            name='providertransaction',
            options={'ordering': ['-date_created'], 'verbose_name': 'Transaction - Provider'},
        ),
        migrations.AlterModelOptions(
            name='usertransaction',
            options={'ordering': ['-date_created'], 'verbose_name': 'Transaction - User'},
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
