# Generated by Django 2.0.6 on 2019-04-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20190401_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_payout_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='provider',
            name='payout_method',
            field=models.CharField(choices=[('default', 'Default - manual end of month'), ('user_bitcoin', 'User - FH provider + FH user'), ('provider_bitcoin', 'Provider - FH postback')], default='default', max_length=32),
        ),
    ]
