# Generated by Django 2.0.6 on 2019-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20190401_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertransaction',
            name='payout_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='payout_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
