# Generated by Django 2.0.6 on 2019-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20190401_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btcprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='btcprice',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='price',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0.0001, max_digits=12),
        ),
        migrations.AlterField(
            model_name='providertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
