# Generated by Django 2.0.6 on 2019-04-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20190401_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_payout_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
