# Generated by Django 2.0.6 on 2019-04-01 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20190401_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='amount',
            new_name='desktop',
        ),
        migrations.RemoveField(
            model_name='price',
            name='type',
        ),
        migrations.AddField(
            model_name='price',
            name='mobile',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.000100000000000000004792173602385929598312941379845142364501953125'), max_digits=12),
        ),
    ]
