# Generated by Django 2.0.6 on 2019-04-01 19:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20190401_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='id',
        ),
        migrations.AlterField(
            model_name='price',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2, primary_key=True, serialize=False),
        ),
    ]
