# Generated by Django 2.2 on 2019-04-20 18:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_auto_20190420_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
