# Generated by Django 2.2 on 2019-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_auto_20190420_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default='', verbose_name='ip')),
                ('is_vpn', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='vpn',
            index=models.Index(fields=['ip'], name='survey_vpn_ip_5b3e21_idx'),
        ),
    ]
