# Generated by Django 2.2 on 2019-04-24 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_auto_20190422_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefIdHistory',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('provider_user_id', models.TextField(blank=True, default='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_id_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='refidhistory',
            index=models.Index(fields=['user'], name='survey_refi_user_id_dffdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='refidhistory',
            index=models.Index(fields=['id'], name='survey_refi_id_c58906_idx'),
        ),
    ]
