# Generated by Django 2.2 on 2019-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_auto_20190424_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='refidhistory',
            name='bitcoin_address',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.IntegerField(choices=[('new', 0), ('success', 1), ('has_contradicting', 2), ('changed_ip', 3), ('solve_too_often', 4), ('zombie', 5), ('bot', 6)], default=0),
        ),
    ]
