# Generated by Django 2.2 on 2019-05-05 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_auto_20190505_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refidhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_id_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
