# Generated by Django 2.2 on 2019-05-12 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_auto_20190505_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='desktop',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00020000000000000000958434720477185919662588275969028472900390625'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='mobile',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00020000000000000000958434720477185919662588275969028472900390625'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_payout_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='provider payout percent to user'),
        ),
    ]
