# Generated by Django 2.2 on 2019-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_auto_20190512_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='postback_url',
            field=models.TextField(blank=True, default='', help_text='Possible variables: {provider_user_id} {country} {price} {bitcoin_address}', null=True, verbose_name='postback url'),
        ),
    ]
