# Generated by Django 2.2 on 2019-05-15 22:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_auto_20190512_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('selector', models.CharField(max_length=32)),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tag_url', models.CharField(max_length=256)),
                ('tag_id', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('rate', models.IntegerField(default=1)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.BannerType')),
            ],
        ),
    ]
