# Generated by Django 2.2 on 2019-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0042_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
