# Generated by Django 2.2 on 2019-05-20 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
