# Generated by Django 2.2 on 2019-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_article_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannertype',
            name='device',
            field=models.CharField(choices=[('MOBILE', 'DEVICE_MOBILE'), ('DESKTOP', 'DEVICE_DESKTOP')], default='DEVICE_DESKTOP', max_length=32),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postback_url',
            field=models.TextField(blank=True, default='', help_text='Possible variables: {provider_user_id} {country} {price} {ip} {bitcoin_address}', null=True, verbose_name='postback url'),
        ),
    ]
