# Generated by Django 2.2 on 2019-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_auto_20190522_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannertype',
            name='device',
        ),
        migrations.AddField(
            model_name='banner',
            name='device',
            field=models.CharField(choices=[('MOBILE', 'DEVICE_MOBILE'), ('DESKTOP', 'DEVICE_DESKTOP')], default='DEVICE_DESKTOP', max_length=32),
        ),
    ]
