# Generated by Django 2.2 on 2019-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0047_auto_20190526_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('vote', 'vote'), ('textarea', 'textarea'), ('radio', 'radio'), ('checkbox', 'checkbox')], default='radio', max_length=32),
        ),
    ]
