# Generated by Django 2.2 on 2019-05-28 21:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_auto_20190526_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='payout_hide',
            field=models.BooleanField(default=False, verbose_name='Hide user payout'),
        ),
        migrations.AlterField(
            model_name='price',
            name='desktop',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0025000000000000000520417042793042128323577344417572021484375'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='mobile',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0025000000000000000520417042793042128323577344417572021484375'), max_digits=12),
        ),
    ]
