# Generated by Django 2.2 on 2019-05-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_auto_20190528_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(default='cents', max_length=32),
        ),
    ]
