# Generated by Django 2.2 on 2019-05-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0050_auto_20190528_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='question_count',
            field=models.IntegerField(default=10, verbose_name='Count of questions per survey'),
        ),
    ]
