# Generated by Django 2.2 on 2019-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0051_provider_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='postback_url',
            field=models.TextField(blank=True, default='', help_text='Possible variables: {provider_user_id} {country} {price} {ip} {bitcoin_address} {txn_id}', null=True, verbose_name='postback url'),
        ),
    ]
