# Generated by Django 2.2 on 2019-05-30 20:56

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0052_auto_20190529_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannertype',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=4),
        ),
        migrations.AlterField(
            model_name='price',
            name='desktop',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0002249999999999999938417316602823348148376680910587310791015625'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='mobile',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0002249999999999999938417316602823348148376680910587310791015625'), max_digits=12),
        ),
    ]
