# Generated by Django 2.2 on 2019-06-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0054_auto_20190530_2102'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['user', 'solved'], name='survey_surv_user_id_db75cd_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['id'], name='survey_surv_id_e3c41a_idx'),
        ),
    ]
