# Generated by Django 2.2 on 2019-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0055_auto_20190601_1930'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['id'], name='survey_choi_id_8e9fbe_idx'),
        ),
    ]
