# Generated by Django 2.2 on 2019-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0057_auto_20190602_1105'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providertransaction',
            index=models.Index(fields=['provider'], name='survey_prov_provide_50932e_idx'),
        ),
        migrations.AddIndex(
            model_name='usertransaction',
            index=models.Index(fields=['user'], name='survey_user_user_id_2730c1_idx'),
        ),
    ]
