# Generated by Django 2.2 on 2019-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0058_auto_20190602_1219'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['user'], name='survey_surv_user_id_ba58c4_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['solved', 'user'], name='survey_surv_solved_d7c763_idx'),
        ),
    ]
