# Generated by Django 2.2 on 2019-06-09 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0059_auto_20190602_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('survey', models.IntegerField(default=0)),
                ('questions', models.IntegerField(default=0)),
                ('survey_success', models.IntegerField(default=0)),
                ('survey_unsuccess', models.IntegerField(default=0)),
                ('transaction', models.IntegerField(default=0)),
                ('users_registered', models.IntegerField(default=0)),
            ],
        ),
    ]
