# Generated by Django 2.2 on 2019-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0060_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
