# Generated by Django 2.2 on 2019-06-15 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0061_article_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserBanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timeout', models.IntegerField(default=0)),
                ('suspend_till', models.DateTimeField(blank=True, default=None, null=True)),
                ('reason', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ban_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
