# Generated by Django 2.2.2 on 2019-06-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0063_auto_20190615_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfingerprint',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='userfingerprint',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
        migrations.DeleteModel(
            name='UserFingerprint',
        ),
    ]
