# Generated by Django 2.2.2 on 2019-06-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0065_auto_20190620_0600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('country', 'provider')},
        ),
    ]
