# Generated by Django 2.2.2 on 2019-06-20 06:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0066_auto_20190620_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_static_postback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='static_postback_countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_countries.fields.CountryField(blank=True, max_length=2, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='provider',
            name='static_postback_desktop',
            field=models.TextField(blank=True, default='', help_text='Possible variables: {provider_user_id} {country} {price} {ip} {bitcoin_address} {txn_id}', null=True, verbose_name='static postback desktop'),
        ),
        migrations.AddField(
            model_name='provider',
            name='static_postback_mobile',
            field=models.TextField(blank=True, default='', help_text='Possible variables: {provider_user_id} {country} {price} {ip} {bitcoin_address} {txn_id}', null=True, verbose_name='static postback mobile'),
        ),
    ]
