# Generated by Django 2.2.2 on 2019-06-23 18:04

import django.contrib.postgres.fields
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0067_auto_20190620_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='static_postback_countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_countries.fields.CountryField(blank=True, max_length=2, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
