# Generated by Django 2.2.2 on 2019-06-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0068_auto_20190623_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='device',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1),
        ),
    ]
