# Generated by Django 2.2.2 on 2019-06-25 20:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0069_survey_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('mobile', models.DecimalField(decimal_places=8, default=Decimal('0.0002249999999999999938417316602823348148376680910587310791015625'), max_digits=12)),
                ('desktop', models.DecimalField(decimal_places=8, default=Decimal('0.0002249999999999999938417316602823348148376680910587310791015625'), max_digits=12)),
                ('provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Provider')),
            ],
            options={
                'verbose_name': 'Price - USD',
                'ordering': ['country'],
                'unique_together': {('country', 'provider')},
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
