# Generated by Django 2.2.2 on 2019-07-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0072_auto_20190625_2006'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['date'], name='survey_metr_date_89a497_idx'),
        ),
    ]
